### ISSUE TITLE
provide Makefile

### ISSUE THREAD

**Issue by jniggemann** [Stefanqn/Bewerbung#14]
It would be convenient for users if you provided a Makefile

**Comment by Stefanqn** [comment]
how so? isn't it just compiling the latex file you need?

**Comment by jniggemann** [comment]
I'm lazy, so I created a Makefile with targets to compile the latex file to PDF as well as to clean up - perhaps others are as lazy as me? ;-) OTOH, this adds a dependency...

**Comment by Stefanqn** [comment]
isn't that already already managed by your IDE?

**Comment by jniggemann** [comment]
No IDE, I'm using GNU nano to edit my files. But I reckon this may not be a common usecase, so I'm closing this.
