### ISSUE TITLE
Grafiken und Unterschrift in Anschreiben werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by d4k0** [Stefanqn/Bewerbung#16]
Hallo,

ich wollte heute das erste Mal seit Dezember 2019 die Vorlage (danke dafür!) verwenden. Zunächst habe ich alle Pakete in MiKTeX aktualisiert, anschließend habe ich das Anschreiben in TeXStudio erstellen lassen. Der Prozess lief ohne Fehler durch. Allerdings werden die Grafiken und die Unterschrift nicht mehr angezeigt, stattdessen wird der Pfad zur jeweiligen Daten ausgegeben:

![anschreiben](https://user-images.githubusercontent.com/10982825/95261275-68830e00-082a-11eb-80cc-f5894ff477a7.jpg)

Beim Lebenslauf gibt es hingegen keine Probleme. Unter Mac OS habe ich mit einem frisch installierten BasicTeX das gleiche Problem. In TeXStudio werden im Log nur folgende Hinweise angezeigt (ist jetzt eigentlich nichts kritisches dabei):

![2020-10-06_23-22-14](https://user-images.githubusercontent.com/10982825/95261563-e7784680-082a-11eb-9ec1-8de167b436d5.png)

Leider konnte ich auch nach einigen Stunden den Fehler nicht finden. Ich würde mich über Hilfe sehr freuen.

**Comment by Stefanqn** [comment]
Hallo, 

ich kann zumindest bestätigen, dass es nicht an deiner Installation liegt. 

Ich habe es mit einem aktuellen texlive image probiert (miktex war 2 Jahre alt):
```
git clone https://github.com/Stefanqn/Bewerbung.git

docker run --rm -it -v //e/Git/BewerbungDocker/Bewerbung:/home adnrv/texlive /bin/bash -c '
cd Vorlage &&
tlmgr update --self &&
tlmgr install texliveonfly &&
tlmgr install babel-german &&
ln -s /usr/bin/python2 /usr/bin/python &&
mkdir -p build &&
TEX_LIVE_ARGS=\"-synctex=1 -interaction=nonstopmode -output-directory=build --shell-escape\" &&
texliveonfly  --arguments=\"${TEX_LIVE_ARGS}\" cv.tex &&
texliveonfly  --arguments=\"${TEX_LIVE_ARGS}\" anschreiben.tex
'
```

**Comment by Simon2105** [comment]
Hi, 
erstmal vielen Dank für die geniale Vorlage.
Zum Problem: 
\usepackage{graphicx} in anschreiben.tex und die Unterschrift wird wieder angezeigt (zumindest bei mir)

**Comment by d4k0** [comment]
@Simon2105 
Super, damit werden die Unterschrift und die Icons wieder angezeigt!

**Comment by SpectreJan** [comment]
Hi,
Danke für die Vorlage und sorry für den necrobump, aber ich bin in texlive auch auf das Problem gestossen und habe das Problem auch in Bewerbung_Komplett.tex gefunden. 

Meine texlive version:  pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020/Arch Linux)

Das Problem in der Vorlage_Anschreiben.sty ist die Reihenfolge der `RequirePackage.` Wenn man das `\RequirePackge{graphicx}` vor das `\RequirePackage{GemeinsameDaten}` zieht funktioniert es wieder in Bewerbung_Komplett sowie in anschreiben.tex ohne https://github.com/Stefanqn/Bewerbung/commit/d9be7e5a9b046caaeb6a69210785e784d0b66df6 

Einen Fix habe ich hier https://github.com/SpectreJan/Bewerbung/commit/a1f623bbceb2eb97c52d24b39253755d1e4d714f falls du/ihr es nochmal testen wollt.
Kann hier gerne einen PullRequest stellen.

Theoretisch könnte manes auch direkt in GemeinsameDaten.sty ziehen da das man eigentlich es vor das `\RequirePackage[export]{adjustbox}` ziehen muss. Keine Ahnung wieso, Latex Voodo für mich.

Cheers,
Jan

**Comment by Stefanqn** [comment]
merged (fix #17)
