### ISSUE TITLE
Arbeitgebername über zwei Zeilen

### ISSUE THREAD

**Issue by toha79** [Stefanqn/Bewerbung#19]
Hi Stefan,

danke für die prima Vorlage!
Einer meiner Arbeitgeber hat einen sehr lagen Namen, welcher sich über zwei Zeilen erstreckt, wenn ich ihn in
`\eintragL{\seit[04.2006]{{\small seit} \hphantom{--}}}{laaaaaaaaaaaaaaaanger Name}{}{Stadt}{%`
eintrage. Leider rutschen die "items" nicht weiter runter, so dass sich Name und Items überlappen.
Wie und wo könnte man das korrigieren?

Grüße
Torsten

**Comment by Stefanqn** [comment]
so?
```
\eintragL{\zeit[09.2018-12.2018]}{Blablabla / Südafrika Stellenbosch / Südafrika Stellenbosch / Südafrika Stellenbosch}{}{Pinneberg}{%
	\vspace{0.5\baselineskip}
	xxx
}
```

**Comment by toha79** [comment]
Perfekt! Danke.
