### ISSUE TITLE
Kompiler Fehler

### ISSUE THREAD

**Issue by Mebus** [Stefanqn/Bewerbung#5]
Hallo, beim Kompilieren von anschreiben.tex bekomme ich diesen Fehler:

<code>
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver: hpdftex.

(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/bookmark.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/bkm-pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hyphsubst.sty

! Package hyphsubst Error: Unknown pattern `ngerman-x-latest'.

See the hyphsubst package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.223 \ProcessOptions*
                      \relax
? 
</code>

Woran kann das liegen?

Mebus

**Comment by Stefanqn** [comment]
Ich nehme an, dass dein Paket zur Worttrennung 'ngerman-x-latest' nicht kennt. Einfach durch ein anderes ersetzen.
