### ISSUE TITLE
Anschreiben mehrere Seiten

### ISSUE THREAD

**Issue by noxin911** [Stefanqn/Bewerbung#7]
Hallo :),

danke für die Top Vorlage ... ich wollte sie derzeit verwenden, jedoch habe ich das Problem, dass das Layout nicht geeignet ist, sollte das Anschreiben (wenn dies auch nicht üblich ist) über mehrere Seiten gehen sollte.

Gibt es hierfür einen schnellen fix?

Danke :)

**Comment by Stefanqn** [comment]
kurz: nein.

Das Problem ist bekannt und dokumentiert. Falls du es selbst lösen willst am Besten die bestehende Vorlage sichten und mit Hilfe der Komascript Doku anpassen.
